import type { StaticProblem } from '../bank';

export const GEOMETRY_PROBLEMS: Record<string, StaticProblem[]> = {
  'geo-01': [
    {
      problem_text: 'A triangle has angles measuring $50°$ and $60°$. What is the measure of the third angle?',
      correct_answer: '70',
      explanation: 'The sum of interior angles in any triangle is $180°$. So the third angle is $180° - 50° - 60° = 70°$.',
      hints: [
        'Recall the triangle angle sum property: all interior angles add up to a specific value.',
        'The sum of all three angles in a triangle is $180°$.',
        'Subtract the two known angles from $180°$: $180° - 50° - 60° = ?$',
      ],
      difficulty: 3,
    },
    {
      problem_text: 'A quadrilateral has three angles measuring $90°$, $85°$, and $110°$. What is the fourth angle?',
      correct_answer: '75',
      explanation: 'The sum of interior angles of a quadrilateral is $360°$. The fourth angle is $360° - 90° - 85° - 110° = 75°$.',
      hints: [
        'Think about how many degrees are in the interior angles of a four-sided shape.',
        'The sum of interior angles in a quadrilateral is $360°$.',
        'Calculate $360° - 90° - 85° - 110°$ to find the missing angle.',
      ],
      difficulty: 3,
    },
    {
      problem_text: 'An isosceles triangle has a base angle of $65°$. What is the measure of the vertex angle?',
      correct_answer: '50',
      explanation: 'In an isosceles triangle, the two base angles are equal. So both base angles are $65°$. The vertex angle is $180° - 65° - 65° = 50°$.',
      hints: [
        'In an isosceles triangle, two sides are equal and so are their opposite angles.',
        'Both base angles are $65°$. Use the triangle angle sum to find the vertex angle.',
        'The vertex angle is $180° - 65° - 65° = 50°$.',
      ],
      difficulty: 3,
    },
    {
      problem_text: 'A circle has a radius of $7$ cm. What is the diameter?',
      correct_answer: '14',
      explanation: 'The diameter of a circle is twice the radius. So $d = 2r = 2 \\times 7 = 14$ cm.',
      hints: [
        'The diameter passes through the centre and touches both sides of the circle.',
        'The diameter is related to the radius by a simple multiplication.',
        'Diameter $= 2 \\times \\text{radius} = 2 \\times 7 = 14$ cm.',
      ],
      difficulty: 3,
    },
    {
      problem_text: 'How many sides does a regular hexagon have, and what is the sum of its interior angles?',
      correct_answer: '720',
      explanation: 'A hexagon has $6$ sides. The sum of interior angles of any polygon is $(n - 2) \\times 180°$, so $(6 - 2) \\times 180° = 4 \\times 180° = 720°$.',
      hints: [
        'The prefix "hex" tells you the number of sides.',
        'Use the formula $(n - 2) \\times 180°$ for the sum of interior angles, where $n$ is the number of sides.',
        'Substitute $n = 6$: $(6 - 2) \\times 180° = 4 \\times 180° = 720°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'A triangle has angles measuring $35°$ and $90°$. What is the third angle?',
      correct_answer: '55',
      explanation: 'The sum of angles in a triangle is $180°$. The third angle is $180° - 35° - 90° = 55°$.',
      hints: [
        'This is a right triangle since one angle is $90°$.',
        'All three angles must sum to $180°$.',
        'Calculate $180° - 35° - 90° = 55°$.',
      ],
      difficulty: 3,
    },
    {
      problem_text: 'What is the sum of the interior angles of a pentagon?',
      correct_answer: '540',
      explanation: 'A pentagon has $5$ sides. Using the formula $(n - 2) \\times 180°$: $(5 - 2) \\times 180° = 3 \\times 180° = 540°$.',
      hints: [
        'A pentagon has $5$ sides. There is a formula for interior angle sums using the number of sides.',
        'The formula is $(n - 2) \\times 180°$.',
        'Substitute $n = 5$: $(5 - 2) \\times 180° = 3 \\times 180° = 540°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'An equilateral triangle has all sides equal. What is the measure of each interior angle?',
      correct_answer: '60',
      explanation: 'In an equilateral triangle all three angles are equal. Since they must sum to $180°$, each angle is $\\frac{180°}{3} = 60°$.',
      hints: [
        'If all sides are equal, then all angles are equal too.',
        'Three equal angles must sum to $180°$.',
        'Each angle $= \\frac{180°}{3} = 60°$.',
      ],
      difficulty: 3,
    },
    {
      problem_text: 'What is each interior angle of a regular octagon?',
      correct_answer: '135',
      explanation: 'An octagon has $8$ sides. The sum of interior angles is $(8 - 2) \\times 180° = 1080°$. Each angle in a regular octagon is $\\frac{1080°}{8} = 135°$.',
      hints: [
        'An octagon has $8$ sides. First find the total sum of interior angles.',
        'Sum $= (8 - 2) \\times 180° = 1080°$.',
        'Divide by the number of sides: $\\frac{1080°}{8} = 135°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'A circle has a diameter of $20$ cm. What is its radius?',
      correct_answer: '10',
      explanation: 'The radius is half the diameter: $r = \\frac{d}{2} = \\frac{20}{2} = 10$ cm.',
      hints: [
        'The radius and diameter are related by a factor of $2$.',
        'The radius is half the diameter.',
        '$r = \\frac{20}{2} = 10$ cm.',
      ],
      difficulty: 3,
    },
    {
      problem_text: 'A triangle has angles in the ratio $1:2:3$. What is the largest angle?',
      correct_answer: '90',
      explanation: 'The angles are $1k$, $2k$, and $3k$ where $1k + 2k + 3k = 180°$. So $6k = 180°$ and $k = 30°$. The largest angle is $3k = 90°$.',
      hints: [
        'Let the angles be $k$, $2k$, and $3k$. They must sum to $180°$.',
        '$k + 2k + 3k = 6k = 180°$, so $k = 30°$.',
        'The largest angle is $3 \\times 30° = 90°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'What is the sum of the interior angles of a decagon (10-sided polygon)?',
      correct_answer: '1440',
      explanation: 'Using the formula $(n - 2) \\times 180°$ with $n = 10$: $(10 - 2) \\times 180° = 8 \\times 180° = 1440°$.',
      hints: [
        'A decagon has $10$ sides.',
        'Use the interior angle sum formula: $(n - 2) \\times 180°$.',
        '$(10 - 2) \\times 180° = 8 \\times 180° = 1440°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'An isosceles triangle has a vertex angle of $40°$. What is each base angle?',
      correct_answer: '70',
      explanation: 'The two base angles are equal. Let each be $b$. Then $40° + 2b = 180°$, so $2b = 140°$ and $b = 70°$.',
      hints: [
        'In an isosceles triangle, the two base angles are equal.',
        'Set up the equation: $40° + 2b = 180°$.',
        '$2b = 140°$, so $b = 70°$.',
      ],
      difficulty: 3,
    },
  ],

  'geo-02': [
    {
      problem_text: 'Two angles are supplementary. One angle measures $115°$. What is the other angle?',
      correct_answer: '65',
      explanation: 'Supplementary angles add up to $180°$. So the other angle is $180° - 115° = 65°$.',
      hints: [
        'Supplementary angles have a special sum. Do you remember what it is?',
        'Supplementary angles add up to $180°$.',
        'Calculate $180° - 115° = 65°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'Two angles are complementary. One angle measures $37°$. What is the other angle?',
      correct_answer: '53',
      explanation: 'Complementary angles add up to $90°$. So the other angle is $90° - 37° = 53°$.',
      hints: [
        'Complementary angles have a specific sum — think of a right angle.',
        'Complementary angles add up to $90°$.',
        'Calculate $90° - 37° = 53°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'Two parallel lines are cut by a transversal. One alternate interior angle measures $48°$. What is the other alternate interior angle?',
      correct_answer: '48',
      explanation: 'When two parallel lines are cut by a transversal, alternate interior angles are equal. So the other angle is also $48°$.',
      hints: [
        'When parallel lines are cut by a transversal, certain angle pairs have special relationships.',
        'Alternate interior angles are on opposite sides of the transversal, between the parallel lines.',
        'Alternate interior angles are always equal when lines are parallel, so the answer is $48°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'A transversal crosses two parallel lines. A co-interior (same-side interior) angle measures $125°$. What is the other co-interior angle?',
      correct_answer: '55',
      explanation: 'Co-interior angles (also called consecutive interior angles or same-side interior angles) are supplementary when lines are parallel. So the other angle is $180° - 125° = 55°$.',
      hints: [
        'Co-interior angles are between the parallel lines, on the same side of the transversal.',
        'Co-interior angles are supplementary — they add up to $180°$.',
        'Calculate $180° - 125° = 55°$.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'The exterior angle of a triangle is $130°$. The two non-adjacent interior angles are $x°$ and $55°$. Find $x$.',
      correct_answer: '75',
      explanation: 'The exterior angle of a triangle equals the sum of the two non-adjacent interior angles. So $130° = x + 55°$, giving $x = 130° - 55° = 75°$.',
      hints: [
        'There is a theorem relating an exterior angle of a triangle to the interior angles.',
        'The exterior angle theorem states that an exterior angle equals the sum of the two remote (non-adjacent) interior angles.',
        'Set up the equation: $x + 55° = 130°$, so $x = 75°$.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Two angles are supplementary. One angle is three times the other. What is the smaller angle?',
      correct_answer: '45',
      explanation: 'Let the smaller angle be $x$. Then $x + 3x = 180°$, so $4x = 180°$ and $x = 45°$.',
      hints: [
        'Supplementary angles add up to $180°$. Set up an equation using this fact.',
        'Let the smaller angle be $x$. The larger angle is $3x$. Write $x + 3x = 180°$.',
        '$4x = 180°$, so $x = 45°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'Two parallel lines are cut by a transversal. A corresponding angle measures $72°$. What is the other corresponding angle?',
      correct_answer: '72',
      explanation: 'When two parallel lines are cut by a transversal, corresponding angles are equal. The other corresponding angle is also $72°$.',
      hints: [
        'Corresponding angles are in the same position relative to the transversal at each intersection.',
        'When lines are parallel, corresponding angles are always equal.',
        'The other corresponding angle is $72°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'Two complementary angles are in the ratio $2:3$. What is the larger angle?',
      correct_answer: '54',
      explanation: 'Let the angles be $2k$ and $3k$. Since they are complementary: $2k + 3k = 90°$, so $5k = 90°$ and $k = 18°$. The larger angle is $3 \\times 18° = 54°$.',
      hints: [
        'Complementary angles sum to $90°$. Express both angles using a variable.',
        '$2k + 3k = 90°$ gives $k = 18°$.',
        'The larger angle is $3k = 3 \\times 18° = 54°$.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Vertically opposite angles are formed at an intersection. If one angle is $63°$, what is the vertically opposite angle?',
      correct_answer: '63',
      explanation: 'Vertically opposite angles are always equal. So the vertically opposite angle is also $63°$.',
      hints: [
        'When two lines cross, they form two pairs of vertically opposite angles.',
        'Vertically opposite angles are the angles that face each other across the intersection point.',
        'Vertically opposite angles are always equal, so the answer is $63°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'Two lines intersect. One of the four angles formed is $118°$. What is the angle adjacent to it?',
      correct_answer: '62',
      explanation: 'Adjacent angles at an intersection point are supplementary (they form a straight line). So the adjacent angle is $180° - 118° = 62°$.',
      hints: [
        'Adjacent angles on a straight line have a special relationship.',
        'They are supplementary, meaning they add up to $180°$.',
        '$180° - 118° = 62°$.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'The exterior angle of a triangle is $140°$. If the two non-adjacent interior angles are equal, what is each one?',
      correct_answer: '70',
      explanation: 'The exterior angle equals the sum of the two non-adjacent interior angles. If each is $x$, then $2x = 140°$, so $x = 70°$.',
      hints: [
        'Use the exterior angle theorem: the exterior angle equals the sum of the two remote interior angles.',
        'Since both non-adjacent interior angles are equal, let each be $x$. Then $2x = 140°$.',
        '$x = \\frac{140°}{2} = 70°$.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'A transversal crosses two parallel lines. One alternate exterior angle is $105°$. What is the other alternate exterior angle?',
      correct_answer: '105',
      explanation: 'Alternate exterior angles are equal when the lines are parallel. So the other angle is also $105°$.',
      hints: [
        'Alternate exterior angles are outside the parallel lines, on opposite sides of the transversal.',
        'Like alternate interior angles, alternate exterior angles are equal when lines are parallel.',
        'The other alternate exterior angle is $105°$.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Angles on a straight line sum to $180°$. Three angles on a straight line measure $x°$, $55°$, and $70°$. Find $x$.',
      correct_answer: '55',
      explanation: 'Angles on a straight line add up to $180°$. So $x + 55° + 70° = 180°$, which gives $x = 180° - 125° = 55°$.',
      hints: [
        'All angles along one side of a straight line sum to $180°$.',
        'Write the equation: $x + 55° + 70° = 180°$.',
        '$x = 180° - 125° = 55°$.',
      ],
      difficulty: 4,
    },
  ],

  'geo-03': [
    {
      problem_text: 'Find the area of a rectangle with length $12$ cm and width $5$ cm.',
      correct_answer: '60',
      explanation: 'The area of a rectangle is $A = l \\times w = 12 \\times 5 = 60$ cm².',
      hints: [
        'The area of a rectangle is found by multiplying two of its dimensions.',
        'Use the formula $A = \\text{length} \\times \\text{width}$.',
        'Calculate $A = 12 \\times 5 = 60$ cm².',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'Find the area of a triangle with base $10$ cm and height $6$ cm.',
      correct_answer: '30',
      explanation: 'The area of a triangle is $A = \\frac{1}{2} \\times b \\times h = \\frac{1}{2} \\times 10 \\times 6 = 30$ cm².',
      hints: [
        'A triangle\'s area is a fraction of the area of a related rectangle.',
        'Use the formula $A = \\frac{1}{2} \\times \\text{base} \\times \\text{height}$.',
        'Calculate $A = \\frac{1}{2} \\times 10 \\times 6 = 30$ cm².',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'Find the circumference of a circle with radius $7$ cm. Give your answer in terms of $\\pi$.',
      correct_answer: '14pi',
      explanation: 'The circumference of a circle is $C = 2\\pi r = 2\\pi \\times 7 = 14\\pi$ cm.',
      hints: [
        'The circumference formula involves $\\pi$ and the radius.',
        'Use $C = 2\\pi r$.',
        'Substitute $r = 7$: $C = 2\\pi \\times 7 = 14\\pi$ cm.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'Find the area of a circle with diameter $10$ cm. Give your answer in terms of $\\pi$.',
      correct_answer: '25pi',
      explanation: 'The radius is $r = \\frac{10}{2} = 5$ cm. The area is $A = \\pi r^2 = \\pi \\times 5^2 = 25\\pi$ cm².',
      hints: [
        'First convert the diameter to a radius.',
        'The radius is half the diameter: $r = 5$ cm. Now use $A = \\pi r^2$.',
        'Calculate $A = \\pi \\times 5^2 = 25\\pi$ cm².',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'An L-shaped room is made of two rectangles: one is $8$ m by $4$ m and the other is $5$ m by $3$ m. What is the total area?',
      correct_answer: '47',
      explanation: 'Break the L-shape into two rectangles. Area $= (8 \\times 4) + (5 \\times 3) = 32 + 15 = 47$ m².',
      hints: [
        'For composite shapes, break them into simpler shapes you know how to calculate.',
        'Find the area of each rectangle separately, then add them together.',
        'Area $= (8 \\times 4) + (5 \\times 3) = 32 + 15 = 47$ m².',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Find the area of a parallelogram with base $9$ cm and perpendicular height $4$ cm.',
      correct_answer: '36',
      explanation: 'The area of a parallelogram is $A = b \\times h = 9 \\times 4 = 36$ cm².',
      hints: [
        'A parallelogram\'s area formula is similar to a rectangle\'s.',
        'Use $A = \\text{base} \\times \\text{perpendicular height}$.',
        '$A = 9 \\times 4 = 36$ cm².',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'Find the area of a trapezium with parallel sides $6$ cm and $10$ cm and height $4$ cm.',
      correct_answer: '32',
      explanation: 'The area of a trapezium is $A = \\frac{1}{2}(a + b) \\times h = \\frac{1}{2}(6 + 10) \\times 4 = \\frac{1}{2} \\times 16 \\times 4 = 32$ cm².',
      hints: [
        'The trapezium area formula uses both parallel sides and the height.',
        'Use $A = \\frac{1}{2}(a + b) \\times h$ where $a$ and $b$ are the parallel sides.',
        '$A = \\frac{1}{2}(6 + 10) \\times 4 = \\frac{1}{2} \\times 16 \\times 4 = 32$ cm².',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'A right triangle has legs of length $5$ cm and $12$ cm. What is the length of the hypotenuse?',
      correct_answer: '13',
      explanation: 'By the Pythagorean theorem: $c = \\sqrt{a^2 + b^2} = \\sqrt{5^2 + 12^2} = \\sqrt{25 + 144} = \\sqrt{169} = 13$ cm.',
      hints: [
        'Use the Pythagorean theorem to relate the sides of a right triangle.',
        '$c^2 = a^2 + b^2 = 25 + 144 = 169$.',
        '$c = \\sqrt{169} = 13$ cm.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Find the perimeter of a rectangle with length $15$ cm and width $8$ cm.',
      correct_answer: '46',
      explanation: 'The perimeter of a rectangle is $P = 2(l + w) = 2(15 + 8) = 2 \\times 23 = 46$ cm.',
      hints: [
        'The perimeter is the total distance around the outside of the shape.',
        'A rectangle has two pairs of equal sides. Use $P = 2(l + w)$.',
        '$P = 2(15 + 8) = 2 \\times 23 = 46$ cm.',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'Find the area of a circle with radius $6$ cm. Give your answer in terms of $\\pi$.',
      correct_answer: '36pi',
      explanation: 'The area of a circle is $A = \\pi r^2 = \\pi \\times 6^2 = 36\\pi$ cm².',
      hints: [
        'The area formula for a circle uses $\\pi$ and the radius squared.',
        'Use $A = \\pi r^2$.',
        '$A = \\pi \\times 36 = 36\\pi$ cm².',
      ],
      difficulty: 4,
    },
    {
      problem_text: 'A semicircle has a diameter of $8$ cm. What is its area? Give your answer in terms of $\\pi$.',
      correct_answer: '8pi',
      explanation: 'The radius is $r = 4$ cm. A semicircle is half a circle, so $A = \\frac{1}{2}\\pi r^2 = \\frac{1}{2}\\pi \\times 16 = 8\\pi$ cm².',
      hints: [
        'A semicircle is exactly half of a full circle.',
        'First find the radius: $r = \\frac{8}{2} = 4$ cm. Then use half the circle area formula.',
        '$A = \\frac{1}{2} \\times \\pi \\times 4^2 = \\frac{1}{2} \\times 16\\pi = 8\\pi$ cm².',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'A right triangle has a hypotenuse of $10$ cm and one leg of $6$ cm. What is the other leg?',
      correct_answer: '8',
      explanation: 'By the Pythagorean theorem: $b = \\sqrt{c^2 - a^2} = \\sqrt{10^2 - 6^2} = \\sqrt{100 - 36} = \\sqrt{64} = 8$ cm.',
      hints: [
        'Use the Pythagorean theorem, but rearrange to solve for the missing leg.',
        '$b^2 = c^2 - a^2 = 100 - 36 = 64$.',
        '$b = \\sqrt{64} = 8$ cm.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Find the circumference of a circle with diameter $9$ cm. Give your answer in terms of $\\pi$.',
      correct_answer: '9pi',
      explanation: 'The circumference of a circle is $C = \\pi d = \\pi \\times 9 = 9\\pi$ cm.',
      hints: [
        'There is a circumference formula that uses the diameter directly.',
        'Use $C = \\pi d$.',
        '$C = \\pi \\times 9 = 9\\pi$ cm.',
      ],
      difficulty: 4,
    },
  ],

  'geo-04': [
    {
      problem_text: 'Find the volume of a rectangular prism with length $8$ cm, width $5$ cm, and height $3$ cm.',
      correct_answer: '120',
      explanation: 'The volume of a rectangular prism is $V = l \\times w \\times h = 8 \\times 5 \\times 3 = 120$ cm³.',
      hints: [
        'A rectangular prism\'s volume extends the area of the base into the third dimension.',
        'Use the formula $V = l \\times w \\times h$.',
        'Calculate $V = 8 \\times 5 \\times 3 = 120$ cm³.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Find the surface area of a cube with side length $4$ cm.',
      correct_answer: '96',
      explanation: 'A cube has 6 identical square faces. Surface area $= 6s^2 = 6 \\times 4^2 = 6 \\times 16 = 96$ cm².',
      hints: [
        'Think about how many faces a cube has and the shape of each face.',
        'A cube has 6 square faces, each with area $s^2$.',
        'Surface area $= 6 \\times 4^2 = 6 \\times 16 = 96$ cm².',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Find the volume of a cylinder with radius $3$ cm and height $10$ cm. Give your answer in terms of $\\pi$.',
      correct_answer: '90pi',
      explanation: 'The volume of a cylinder is $V = \\pi r^2 h = \\pi \\times 3^2 \\times 10 = 90\\pi$ cm³.',
      hints: [
        'A cylinder is like a circle extruded along a height. Its volume builds on the area of a circle.',
        'Use $V = \\pi r^2 h$.',
        'Substitute: $V = \\pi \\times 9 \\times 10 = 90\\pi$ cm³.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Find the volume of a cone with radius $6$ cm and height $9$ cm. Give your answer in terms of $\\pi$.',
      correct_answer: '108pi',
      explanation: 'The volume of a cone is $V = \\frac{1}{3}\\pi r^2 h = \\frac{1}{3} \\times \\pi \\times 6^2 \\times 9 = \\frac{1}{3} \\times 324\\pi = 108\\pi$ cm³.',
      hints: [
        'A cone\'s volume is a fraction of the volume of a cylinder with the same base and height.',
        'Use $V = \\frac{1}{3}\\pi r^2 h$. A cone is one-third the volume of its corresponding cylinder.',
        'Calculate $V = \\frac{1}{3} \\times \\pi \\times 36 \\times 9 = \\frac{324\\pi}{3} = 108\\pi$ cm³.',
      ],
      difficulty: 6,
    },
    {
      problem_text: 'Find the volume of a sphere with radius $5$ cm. Give your answer in terms of $\\pi$.',
      correct_answer: '500pi/3',
      explanation: 'The volume of a sphere is $V = \\frac{4}{3}\\pi r^3 = \\frac{4}{3}\\pi \\times 5^3 = \\frac{4}{3} \\times 125\\pi = \\frac{500\\pi}{3}$ cm³.',
      hints: [
        'The sphere volume formula involves the cube of the radius.',
        'Use $V = \\frac{4}{3}\\pi r^3$.',
        'Substitute: $V = \\frac{4}{3}\\pi \\times 125 = \\frac{500\\pi}{3}$ cm³.',
      ],
      difficulty: 6,
    },
    {
      problem_text: 'Find the volume of a cube with side length $7$ cm.',
      correct_answer: '343',
      explanation: 'The volume of a cube is $V = s^3 = 7^3 = 343$ cm³.',
      hints: [
        'A cube has all three dimensions equal.',
        'Use $V = s^3$ where $s$ is the side length.',
        '$V = 7^3 = 343$ cm³.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Find the surface area of a rectangular prism with length $6$ cm, width $4$ cm, and height $3$ cm.',
      correct_answer: '108',
      explanation: 'Surface area $= 2(lw + lh + wh) = 2(6 \\times 4 + 6 \\times 3 + 4 \\times 3) = 2(24 + 18 + 12) = 2 \\times 54 = 108$ cm².',
      hints: [
        'A rectangular prism has three pairs of identical rectangular faces.',
        'Surface area $= 2(lw + lh + wh)$.',
        '$= 2(24 + 18 + 12) = 2 \\times 54 = 108$ cm².',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'A cylinder has a volume of $200\\pi$ cm³ and a radius of $5$ cm. What is its height?',
      correct_answer: '8',
      explanation: 'Using $V = \\pi r^2 h$: $200\\pi = \\pi \\times 25 \\times h$, so $h = \\frac{200}{25} = 8$ cm.',
      hints: [
        'Start with the cylinder volume formula and solve for the unknown.',
        '$200\\pi = \\pi \\times 5^2 \\times h$. Divide both sides by $25\\pi$.',
        '$h = \\frac{200}{25} = 8$ cm.',
      ],
      difficulty: 6,
    },
    {
      problem_text: 'Find the volume of a triangular prism with a base triangle of area $15$ cm² and length $10$ cm.',
      correct_answer: '150',
      explanation: 'The volume of a prism is $V = \\text{base area} \\times \\text{length} = 15 \\times 10 = 150$ cm³.',
      hints: [
        'A prism\'s volume is found by multiplying the cross-sectional area by the length.',
        '$V = \\text{base area} \\times \\text{length}$.',
        '$V = 15 \\times 10 = 150$ cm³.',
      ],
      difficulty: 5,
    },
    {
      problem_text: 'Find the surface area of a sphere with radius $3$ cm. Give your answer in terms of $\\pi$.',
      correct_answer: '36pi',
      explanation: 'The surface area of a sphere is $SA = 4\\pi r^2 = 4\\pi \\times 3^2 = 4\\pi \\times 9 = 36\\pi$ cm².',
      hints: [
        'The sphere surface area formula uses $\\pi$ and the radius squared.',
        'Use $SA = 4\\pi r^2$.',
        '$SA = 4\\pi \\times 9 = 36\\pi$ cm².',
      ],
      difficulty: 6,
    },
    {
      problem_text: 'A cone has a volume of $48\\pi$ cm³ and a height of $9$ cm. What is its radius?',
      correct_answer: '4',
      explanation: 'Using $V = \\frac{1}{3}\\pi r^2 h$: $48\\pi = \\frac{1}{3}\\pi r^2 \\times 9 = 3\\pi r^2$. So $r^2 = 16$ and $r = 4$ cm.',
      hints: [
        'Start with the cone volume formula and solve for $r$.',
        '$48\\pi = \\frac{1}{3}\\pi r^2 \\times 9 = 3\\pi r^2$. Divide both sides by $3\\pi$.',
        '$r^2 = 16$, so $r = 4$ cm.',
      ],
      difficulty: 6,
    },
    {
      problem_text: 'A hemisphere has a radius of $6$ cm. What is its volume? Give your answer in terms of $\\pi$.',
      correct_answer: '144pi',
      explanation: 'A hemisphere is half a sphere. $V = \\frac{1}{2} \\times \\frac{4}{3}\\pi r^3 = \\frac{2}{3}\\pi r^3 = \\frac{2}{3}\\pi \\times 216 = 144\\pi$ cm³.',
      hints: [
        'A hemisphere is exactly half of a sphere.',
        'Use $V = \\frac{2}{3}\\pi r^3$ (half the sphere formula).',
        '$V = \\frac{2}{3}\\pi \\times 6^3 = \\frac{2}{3} \\times 216\\pi = 144\\pi$ cm³.',
      ],
      difficulty: 6,
    },
    {
      problem_text: 'Find the volume of a cylinder with diameter $8$ cm and height $5$ cm. Give your answer in terms of $\\pi$.',
      correct_answer: '80pi',
      explanation: 'The radius is $r = \\frac{8}{2} = 4$ cm. $V = \\pi r^2 h = \\pi \\times 4^2 \\times 5 = \\pi \\times 16 \\times 5 = 80\\pi$ cm³.',
      hints: [
        'First convert the diameter to a radius.',
        'Radius $= 4$ cm. Use $V = \\pi r^2 h$.',
        '$V = \\pi \\times 16 \\times 5 = 80\\pi$ cm³.',
      ],
      difficulty: 5,
    },
  ],
};
