/**
 * Legacy problem pools — migrated from the original practiceMock.ts
 * Covers: pre-alg-02, alg-01, alg-02, alg-04, alg-05, geo-05, trig-01, calc-02
 */
import type { StaticProblem } from '../bank';

export const LEGACY_PROBLEMS: Record<string, StaticProblem[]> = {
  'pre-alg-02': [
    { problem_text: 'Simplify: $\\frac{2}{5} + \\frac{1}{3}$', correct_answer: '11/15', explanation: 'Find common denominator 15: $\\frac{6}{15} + \\frac{5}{15} = \\frac{11}{15}$', hints: ['Find a common denominator for 5 and 3.', 'The common denominator is 15. Convert each fraction.', '$\\frac{2}{5} = \\frac{6}{15}$ and $\\frac{1}{3} = \\frac{5}{15}$. Now add the numerators.'], difficulty: 2 },
    { problem_text: 'Simplify: $\\frac{3}{4} \\times \\frac{2}{7}$', correct_answer: '3/14', explanation: 'Multiply numerators and denominators: $\\frac{3 \\times 2}{4 \\times 7} = \\frac{6}{28} = \\frac{3}{14}$', hints: ['Multiply the numerators together, then the denominators.', '$3 \\times 2 = 6$ and $4 \\times 7 = 28$, giving $\\frac{6}{28}$.', 'Simplify by dividing both by 2: $\\frac{3}{14}$.'], difficulty: 2 },
    { problem_text: 'Simplify: $\\frac{5}{6} - \\frac{1}{4}$', correct_answer: '7/12', explanation: 'Common denominator 12: $\\frac{10}{12} - \\frac{3}{12} = \\frac{7}{12}$', hints: ['Find a common denominator for 6 and 4.', 'The LCM of 6 and 4 is 12.', '$\\frac{10}{12} - \\frac{3}{12} = \\frac{7}{12}$'], difficulty: 2 },
    { problem_text: 'Convert $\\frac{7}{4}$ to a mixed number.', correct_answer: '1 3/4', explanation: '$7 \\div 4 = 1$ remainder $3$, so $\\frac{7}{4} = 1\\frac{3}{4}$', hints: ['Divide the numerator by the denominator.', '$7 \\div 4 = 1$ with remainder $3$.', 'The whole number is 1 and the fraction part is $\\frac{3}{4}$.'], difficulty: 2 },
    { problem_text: 'What is $\\frac{2}{3}$ of 45?', correct_answer: '30', explanation: '$\\frac{2}{3} \\times 45 = \\frac{90}{3} = 30$', hints: ['Multiply 45 by the fraction.', '$45 \\times 2 = 90$.', '$\\frac{90}{3} = 30$.'], difficulty: 3 },
    { problem_text: 'Simplify: $\\frac{3}{8} \\div \\frac{1}{4}$', correct_answer: '3/2', explanation: 'Dividing by a fraction = multiplying by its reciprocal: $\\frac{3}{8} \\times \\frac{4}{1} = \\frac{12}{8} = \\frac{3}{2}$', hints: ['To divide by a fraction, multiply by its reciprocal.', 'The reciprocal of $\\frac{1}{4}$ is $\\frac{4}{1}$.', '$\\frac{3}{8} \\times 4 = \\frac{12}{8} = \\frac{3}{2}$.'], difficulty: 3 },
    { problem_text: 'Convert $0.375$ to a fraction in simplest form.', correct_answer: '3/8', explanation: '$0.375 = \\frac{375}{1000} = \\frac{3}{8}$ (divide by 125).', hints: ['Write it as a fraction over 1000.', '$\\frac{375}{1000}$. Find the GCD of 375 and 1000.', 'GCD is 125: $\\frac{375 \\div 125}{1000 \\div 125} = \\frac{3}{8}$.'], difficulty: 3 },
    { problem_text: 'Arrange in order from least to greatest: $\\frac{2}{3}$, $\\frac{3}{5}$, $\\frac{7}{10}$', correct_answer: '3/5, 2/3, 7/10', explanation: 'Convert to 30ths: $\\frac{20}{30}, \\frac{18}{30}, \\frac{21}{30}$. Order: $\\frac{18}{30} < \\frac{20}{30} < \\frac{21}{30}$', hints: ['Find a common denominator for all three fractions.', 'Use 30: $\\frac{2}{3} = \\frac{20}{30}$, $\\frac{3}{5} = \\frac{18}{30}$, $\\frac{7}{10} = \\frac{21}{30}$.', 'Smallest to largest: $\\frac{3}{5}, \\frac{2}{3}, \\frac{7}{10}$.'], difficulty: 3 },
    { problem_text: 'Simplify: $\\frac{4}{9} + \\frac{5}{6}$', correct_answer: '23/18', explanation: 'Common denominator 18: $\\frac{8}{18} + \\frac{15}{18} = \\frac{23}{18}$', hints: ['Find the LCM of 9 and 6.', 'LCM is 18. Convert: $\\frac{8}{18} + \\frac{15}{18}$.', 'Add: $\\frac{23}{18}$ (or $1\\frac{5}{18}$).'], difficulty: 2 },
    { problem_text: 'What is $2.5 \\times 0.4$?', correct_answer: '1', explanation: '$2.5 \\times 0.4 = 1.0 = 1$', hints: ['You can think of this as $\\frac{5}{2} \\times \\frac{2}{5}$.', 'Multiply: $5 \\times 2 = 10$ and $2 \\times 5 = 10$.', '$\\frac{10}{10} = 1$.'], difficulty: 2 },
  ],
  'alg-01': [
    { problem_text: 'Simplify: $3x + 5 + 2x - 1$', correct_answer: '5x+4', explanation: 'Combine like terms: $3x + 2x = 5x$ and $5 - 1 = 4$, so $5x + 4$.', hints: ['Group the terms with $x$ together and the constants together.', '$3x + 2x = 5x$.', '$5 - 1 = 4$. So the answer is $5x + 4$.'], difficulty: 3 },
    { problem_text: 'Evaluate $2a + 3b$ when $a = 4$ and $b = -1$.', correct_answer: '5', explanation: '$2(4) + 3(-1) = 8 - 3 = 5$', hints: ['Substitute the given values for $a$ and $b$.', '$2(4) = 8$ and $3(-1) = -3$.', '$8 + (-3) = 5$.'], difficulty: 3 },
    { problem_text: 'Simplify: $4(x + 2) - 3x$', correct_answer: 'x+8', explanation: 'Distribute: $4x + 8 - 3x = x + 8$', hints: ['First distribute the 4.', '$4 \\times x + 4 \\times 2 = 4x + 8$.', '$4x + 8 - 3x = x + 8$.'], difficulty: 4 },
    { problem_text: 'Write an expression for "5 more than twice a number $n$".', correct_answer: '2n+5', explanation: 'Twice a number is $2n$, then add 5: $2n + 5$.', hints: ['"Twice a number" means multiply by 2.', 'That gives $2n$.', '"5 more than" means add 5: $2n + 5$.'], difficulty: 3 },
    { problem_text: 'Simplify: $-2(3x - 4) + x$', correct_answer: '-5x+8', explanation: 'Distribute: $-6x + 8 + x = -5x + 8$', hints: ['Distribute $-2$ to both terms inside the brackets.', '$-2 \\times 3x = -6x$ and $-2 \\times (-4) = 8$.', '$-6x + 8 + x = -5x + 8$.'], difficulty: 4 },
    { problem_text: 'Simplify: $\\frac{6x}{3}$', correct_answer: '2x', explanation: 'Divide coefficient: $\\frac{6}{3} = 2$, so $\\frac{6x}{3} = 2x$.', hints: ['Divide the coefficient of $x$ by the denominator.', '$6 \\div 3 = 2$.', 'So $\\frac{6x}{3} = 2x$.'], difficulty: 3 },
    { problem_text: 'Evaluate $x^2 - 3x + 2$ when $x = 5$.', correct_answer: '12', explanation: '$5^2 - 3(5) + 2 = 25 - 15 + 2 = 12$', hints: ['Substitute $x = 5$ into each term.', '$5^2 = 25$, $3(5) = 15$.', '$25 - 15 + 2 = 12$.'], difficulty: 4 },
    { problem_text: 'Simplify: $7y - 2y + 3 - 8$', correct_answer: '5y-5', explanation: 'Combine like terms: $7y - 2y = 5y$ and $3 - 8 = -5$, giving $5y - 5$.', hints: ['Group $y$ terms and constant terms.', '$7y - 2y = 5y$.', '$3 - 8 = -5$. Answer: $5y - 5$.'], difficulty: 3 },
  ],
  'alg-02': [
    { problem_text: 'Solve for $x$: $3x + 5 = 20$', correct_answer: '5', explanation: '$3x = 15$, so $x = 5$.', hints: ['Subtract 5 from both sides.', '$3x = 15$.', 'Divide both sides by 3.'], difficulty: 4 },
    { problem_text: 'Solve for $x$: $7x - 3 = 4x + 9$', correct_answer: '4', explanation: '$3x = 12$, so $x = 4$.', hints: ['Get all $x$ terms on one side.', '$7x - 4x = 9 + 3$, so $3x = 12$.', '$x = 4$.'], difficulty: 5 },
    { problem_text: 'Solve for $y$: $\\frac{y}{3} + 2 = 7$', correct_answer: '15', explanation: '$\\frac{y}{3} = 5$, so $y = 15$.', hints: ['Subtract 2 from both sides.', '$\\frac{y}{3} = 5$.', 'Multiply both sides by 3.'], difficulty: 4 },
    { problem_text: 'Solve for $x$: $2(x + 3) = 16$', correct_answer: '5', explanation: '$2x + 6 = 16$, so $2x = 10$, $x = 5$.', hints: ['Distribute the 2 first.', '$2x + 6 = 16$.', '$2x = 10$, so $x = 5$.'], difficulty: 4 },
    { problem_text: 'Solve for $x$: $5 - 2x = 11$', correct_answer: '-3', explanation: '$-2x = 6$, so $x = -3$.', hints: ['Subtract 5 from both sides.', '$-2x = 6$.', 'Divide by $-2$: $x = -3$.'], difficulty: 4 },
    { problem_text: 'Solve for $x$: $\\frac{2x - 1}{3} = 5$', correct_answer: '8', explanation: '$2x - 1 = 15$, so $2x = 16$, $x = 8$.', hints: ['Multiply both sides by 3.', '$2x - 1 = 15$.', '$2x = 16$, $x = 8$.'], difficulty: 5 },
    { problem_text: 'Solve for $x$: $4(x - 1) + 3 = 2x + 7$', correct_answer: '4', explanation: '$4x - 4 + 3 = 2x + 7$, so $4x - 1 = 2x + 7$, $2x = 8$, $x = 4$.', hints: ['Distribute and simplify the left side.', '$4x - 1 = 2x + 7$.', '$2x = 8$, so $x = 4$.'], difficulty: 5 },
    { problem_text: 'Solve for $x$: $0.5x + 1.5 = 4$', correct_answer: '5', explanation: '$0.5x = 2.5$, so $x = 5$.', hints: ['Subtract 1.5 from both sides.', '$0.5x = 2.5$.', 'Divide by 0.5 (or multiply by 2): $x = 5$.'], difficulty: 4 },
  ],
  'alg-04': [
    { problem_text: 'Solve the system:\n$$x + y = 10$$\n$$x - y = 4$$', correct_answer: '7', explanation: 'Add equations: $2x = 14$, so $x = 7$. Then $y = 3$.', hints: ['Try adding the two equations together.', '$2x = 14$.', '$x = 7$ (and $y = 3$).'], difficulty: 5 },
    { problem_text: 'Solve the system:\n$$2x + y = 8$$\n$$x - y = 1$$', correct_answer: '3', explanation: 'Add equations: $3x = 9$, $x = 3$. Then $y = 2$.', hints: ['Adding the equations eliminates $y$.', '$3x = 9$.', '$x = 3$.'], difficulty: 5 },
    { problem_text: 'Solve the system:\n$$y = 2x + 1$$\n$$y = -x + 7$$', correct_answer: '2', explanation: 'Set equal: $2x + 1 = -x + 7$, so $3x = 6$, $x = 2$.', hints: ['Both expressions equal $y$, so set them equal.', '$2x + 1 = -x + 7$.', '$3x = 6$, so $x = 2$.'], difficulty: 5 },
    { problem_text: 'Solve for $x$:\n$$3x + 2y = 12$$\n$$x + 2y = 8$$', correct_answer: '2', explanation: 'Subtract second from first: $2x = 4$, $x = 2$.', hints: ['Subtract one equation from the other to eliminate $y$.', '$(3x + 2y) - (x + 2y) = 12 - 8$.', '$2x = 4$, so $x = 2$.'], difficulty: 5 },
    { problem_text: 'Solve the system:\n$$2x + 3y = 7$$\n$$x - y = 1$$', correct_answer: '2', explanation: 'From eq 2: $x = y + 1$. Substitute: $2(y+1) + 3y = 7$, so $5y = 5$, $y = 1$, $x = 2$.', hints: ['Solve the second equation for $x$.', '$x = y + 1$. Substitute into the first equation.', '$2(y+1) + 3y = 7 \\Rightarrow 5y = 5 \\Rightarrow y = 1, x = 2$.'], difficulty: 5 },
  ],
  'alg-05': [
    { problem_text: 'Solve: $x^2 - 5x + 6 = 0$', correct_answer: '2', explanation: 'Factor: $(x-2)(x-3) = 0$, so $x = 2$ or $x = 3$. Smallest root: $x = 2$.', hints: ['Try to factorise the quadratic.', 'Find two numbers that multiply to 6 and add to -5.', '$(x-2)(x-3) = 0$, so $x = 2$ or $x = 3$.'], difficulty: 6 },
    { problem_text: 'Solve: $x^2 + 4x = 0$', correct_answer: '0', explanation: 'Factor: $x(x+4) = 0$, so $x = 0$ or $x = -4$. One root: $x = 0$.', hints: ['Factor out $x$.', '$x(x + 4) = 0$.', 'Either $x = 0$ or $x + 4 = 0$.'], difficulty: 5 },
    { problem_text: 'Solve: $x^2 = 49$', correct_answer: '7', explanation: '$x = \\pm 7$. The positive root is $x = 7$.', hints: ['Take the square root of both sides.', '$\\sqrt{49} = 7$.', '$x = 7$ or $x = -7$.'], difficulty: 4 },
    { problem_text: 'Solve: $x^2 - 9 = 0$', correct_answer: '3', explanation: 'Difference of squares: $(x-3)(x+3) = 0$, so $x = 3$ or $x = -3$.', hints: ['This is a difference of squares.', '$x^2 - 9 = (x-3)(x+3)$.', '$x = 3$ or $x = -3$.'], difficulty: 5 },
    { problem_text: 'Factorise: $x^2 + 7x + 12$', correct_answer: '(x+3)(x+4)', explanation: 'Find two numbers that multiply to 12 and add to 7: 3 and 4.', hints: ['Find two numbers whose product is 12 and sum is 7.', '3 and 4 work: $3 \\times 4 = 12$, $3 + 4 = 7$.', '$(x + 3)(x + 4)$.'], difficulty: 6 },
    { problem_text: 'Solve using the quadratic formula: $x^2 - 4x + 3 = 0$', correct_answer: '1', explanation: '$x = \\frac{4 \\pm \\sqrt{16-12}}{2} = \\frac{4 \\pm 2}{2}$. So $x = 3$ or $x = 1$.', hints: ['Use $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$ with $a=1, b=-4, c=3$.', 'Discriminant: $(-4)^2 - 4(1)(3) = 4$.', '$x = \\frac{4 \\pm 2}{2}$, giving $x = 1$ or $x = 3$.'], difficulty: 6 },
    { problem_text: 'Find the discriminant of $2x^2 + 3x - 5 = 0$.', correct_answer: '49', explanation: '$\\Delta = b^2 - 4ac = 9 - 4(2)(-5) = 9 + 40 = 49$', hints: ['The discriminant is $b^2 - 4ac$.', '$a = 2, b = 3, c = -5$.', '$9 - 4(2)(-5) = 9 + 40 = 49$.'], difficulty: 6 },
  ],
  'geo-05': [
    { problem_text: 'A right triangle has legs 5 and 12. Find the hypotenuse.', correct_answer: '13', explanation: '$c = \\sqrt{5^2 + 12^2} = \\sqrt{25 + 144} = \\sqrt{169} = 13$', hints: ['Use the Pythagorean theorem: $a^2 + b^2 = c^2$.', '$5^2 + 12^2 = 25 + 144 = 169$.', '$c = \\sqrt{169} = 13$.'], difficulty: 5 },
    { problem_text: 'A right triangle has hypotenuse 10 and one leg 6. Find the other leg.', correct_answer: '8', explanation: '$b = \\sqrt{10^2 - 6^2} = \\sqrt{100 - 36} = \\sqrt{64} = 8$', hints: ['Rearrange Pythagorean theorem: $b^2 = c^2 - a^2$.', '$10^2 - 6^2 = 100 - 36 = 64$.', '$b = \\sqrt{64} = 8$.'], difficulty: 5 },
    { problem_text: 'Is a triangle with sides 7, 24, 25 a right triangle?', correct_answer: 'yes', explanation: '$7^2 + 24^2 = 49 + 576 = 625 = 25^2$. Yes, it is.', hints: ['Check if $a^2 + b^2 = c^2$ where $c$ is the longest side.', '$7^2 + 24^2 = 49 + 576 = 625$.', '$25^2 = 625$. Since they are equal, yes.'], difficulty: 5 },
    { problem_text: 'Find the distance between points $(0, 0)$ and $(3, 4)$.', correct_answer: '5', explanation: '$d = \\sqrt{3^2 + 4^2} = \\sqrt{9 + 16} = \\sqrt{25} = 5$', hints: ['Use the distance formula (which is the Pythagorean theorem).', '$d = \\sqrt{(3-0)^2 + (4-0)^2}$.', '$\\sqrt{9 + 16} = \\sqrt{25} = 5$.'], difficulty: 5 },
    { problem_text: 'A ladder 15 m long leans against a wall. Its base is 9 m from the wall. How high does it reach?', correct_answer: '12', explanation: '$h = \\sqrt{15^2 - 9^2} = \\sqrt{225 - 81} = \\sqrt{144} = 12$', hints: ['The ladder, wall, and ground form a right triangle.', 'The ladder is the hypotenuse (15 m), the base is one leg (9 m).', '$\\sqrt{225 - 81} = \\sqrt{144} = 12$ m.'], difficulty: 6 },
    { problem_text: 'A right triangle has legs of length 8 and 15. Find the hypotenuse.', correct_answer: '17', explanation: '$c = \\sqrt{8^2 + 15^2} = \\sqrt{64 + 225} = \\sqrt{289} = 17$', hints: ['Apply the Pythagorean theorem.', '$64 + 225 = 289$.', '$\\sqrt{289} = 17$.'], difficulty: 5 },
    { problem_text: 'Find the distance between $(1, 2)$ and $(4, 6)$.', correct_answer: '5', explanation: '$d = \\sqrt{(4-1)^2 + (6-2)^2} = \\sqrt{9 + 16} = 5$', hints: ['Use the distance formula.', '$(4-1)^2 = 9$ and $(6-2)^2 = 16$.', '$\\sqrt{25} = 5$.'], difficulty: 5 },
  ],
  'trig-01': [
    { problem_text: 'In a right triangle, the opposite side is 3 and the hypotenuse is 5. Find $\\sin(\\theta)$.', correct_answer: '3/5', explanation: '$\\sin(\\theta) = \\frac{\\text{opposite}}{\\text{hypotenuse}} = \\frac{3}{5}$', hints: ['Recall: $\\sin = \\frac{\\text{opposite}}{\\text{hypotenuse}}$.', 'The opposite side is 3 and the hypotenuse is 5.', '$\\sin(\\theta) = \\frac{3}{5}$.'], difficulty: 6 },
    { problem_text: 'In a right triangle, the adjacent side is 4 and the hypotenuse is 5. Find $\\cos(\\theta)$.', correct_answer: '4/5', explanation: '$\\cos(\\theta) = \\frac{\\text{adjacent}}{\\text{hypotenuse}} = \\frac{4}{5}$', hints: ['Recall: $\\cos = \\frac{\\text{adjacent}}{\\text{hypotenuse}}$.', 'Adjacent = 4, hypotenuse = 5.', '$\\cos(\\theta) = \\frac{4}{5}$.'], difficulty: 6 },
    { problem_text: 'If $\\sin(\\theta) = \\frac{5}{13}$, find $\\cos(\\theta)$ (assume $\\theta$ is in Q1).', correct_answer: '12/13', explanation: 'Adjacent = $\\sqrt{13^2 - 5^2} = \\sqrt{144} = 12$, so $\\cos(\\theta) = \\frac{12}{13}$.', hints: ['Use the Pythagorean identity or draw the triangle.', 'If opposite = 5 and hypotenuse = 13, find the adjacent side.', '$\\sqrt{169 - 25} = 12$, so $\\cos(\\theta) = \\frac{12}{13}$.'], difficulty: 7 },
    { problem_text: 'Find $\\tan(\\theta)$ if the opposite side is 8 and the adjacent side is 6.', correct_answer: '4/3', explanation: '$\\tan(\\theta) = \\frac{8}{6} = \\frac{4}{3}$', hints: ['Recall: $\\tan = \\frac{\\text{opposite}}{\\text{adjacent}}$.', '$\\tan(\\theta) = \\frac{8}{6}$.', 'Simplify: $\\frac{4}{3}$.'], difficulty: 6 },
    { problem_text: 'What is $\\sin(30°)$?', correct_answer: '1/2', explanation: '$\\sin(30°) = \\frac{1}{2}$ — this is a standard angle.', hints: ['This is one of the standard angles you should memorise.', 'Think of the 30-60-90 triangle with sides 1, $\\sqrt{3}$, 2.', '$\\sin(30°) = \\frac{\\text{opposite}}{\\text{hypotenuse}} = \\frac{1}{2}$.'], difficulty: 6 },
    { problem_text: 'What is $\\cos(60°)$?', correct_answer: '1/2', explanation: '$\\cos(60°) = \\frac{1}{2}$ — from the 30-60-90 triangle.', hints: ['This is a standard angle from the 30-60-90 triangle.', 'In a 30-60-90 triangle, the side adjacent to 60° is the short leg (1) and hypotenuse is 2.', '$\\cos(60°) = \\frac{1}{2}$.'], difficulty: 6 },
    { problem_text: 'What is $\\tan(45°)$?', correct_answer: '1', explanation: 'In a 45-45-90 triangle both legs are equal, so $\\tan(45°) = \\frac{\\text{opp}}{\\text{adj}} = 1$.', hints: ['Think of the 45-45-90 triangle.', 'Both legs are equal in a 45-45-90 triangle.', '$\\tan(45°) = \\frac{\\text{equal leg}}{\\text{equal leg}} = 1$.'], difficulty: 6 },
  ],
  'calc-02': [
    { problem_text: 'Find $\\frac{d}{dx}(x^4)$.', correct_answer: '4x^3', explanation: 'Power rule: $\\frac{d}{dx}(x^n) = nx^{n-1}$, so $4x^3$.', hints: ['Use the power rule.', '$n = 4$, so bring down 4 and reduce the exponent by 1.', '$4x^3$.'], difficulty: 7 },
    { problem_text: 'Find $\\frac{d}{dx}(3x^2 + 5x - 7)$.', correct_answer: '6x+5', explanation: 'Differentiate term by term: $6x + 5 + 0 = 6x + 5$.', hints: ['Differentiate each term separately.', '$\\frac{d}{dx}(3x^2) = 6x$, $\\frac{d}{dx}(5x) = 5$.', 'The derivative of a constant is 0. Answer: $6x + 5$.'], difficulty: 7 },
    { problem_text: 'Find $\\frac{d}{dx}(\\sqrt{x})$.', correct_answer: '1/(2sqrt(x))', explanation: '$\\sqrt{x} = x^{1/2}$, so $\\frac{d}{dx} = \\frac{1}{2}x^{-1/2} = \\frac{1}{2\\sqrt{x}}$.', hints: ['Rewrite $\\sqrt{x}$ as $x^{1/2}$.', 'Apply the power rule with $n = \\frac{1}{2}$.', '$\\frac{1}{2}x^{-1/2} = \\frac{1}{2\\sqrt{x}}$.'], difficulty: 8 },
    { problem_text: 'What is the slope of $f(x) = x^3$ at $x = 2$?', correct_answer: '12', explanation: "$f'(x) = 3x^2$, so $f'(2) = 3(4) = 12$.", hints: ['First find the derivative of $x^3$.', "$f'(x) = 3x^2$.", 'Evaluate at $x = 2$: $3(2^2) = 12$.'], difficulty: 8 },
    { problem_text: 'Find $\\frac{d}{dx}(5)$.', correct_answer: '0', explanation: 'The derivative of any constant is 0.', hints: ['What happens when you differentiate a constant?', 'A constant has no rate of change.', 'The derivative of any constant is 0.'], difficulty: 7 },
    { problem_text: 'Find $\\frac{d}{dx}(x^{-2})$.', correct_answer: '-2x^{-3}', explanation: 'Power rule: $-2x^{-3}$ or equivalently $\\frac{-2}{x^3}$.', hints: ['Use the power rule with $n = -2$.', 'Bring down $-2$ and reduce exponent by 1.', '$-2x^{-3}$.'], difficulty: 8 },
    { problem_text: 'Find $\\frac{d}{dx}(7x)$.', correct_answer: '7', explanation: '$\\frac{d}{dx}(7x) = 7 \\cdot \\frac{d}{dx}(x) = 7 \\cdot 1 = 7$.', hints: ['The derivative of $x$ is 1.', 'Constants multiply through.', '$7 \\times 1 = 7$.'], difficulty: 7 },
  ],
};
